export const AI_TESTS_PLUGIN_ID = '@kb-labs/ai-tests';
export const ARTIFACTS_ROOT = '.kb/artifacts/ai-tests';
export const PLAN_ARTIFACT_PATH = `${ARTIFACTS_ROOT}/ai-tests.plan.json`;
export const RUN_ARTIFACT_PATH = `${ARTIFACTS_ROOT}/ai-tests.run.json`;
export const ITERATIONS_ARTIFACT_PATH = `${ARTIFACTS_ROOT}/ai-tests.iterations.json`;
export const METADATA_ARTIFACT_PATH = `${ARTIFACTS_ROOT}/metadata.json`;
export const AUDIT_ARTIFACT_PATH = `${ARTIFACTS_ROOT}/ai-tests.audit.md`;
export const LOGS_DIR = `${ARTIFACTS_ROOT}/logs`;
export const SUGGESTIONS_DIR = `${ARTIFACTS_ROOT}/suggestions`;

export const DEFAULT_TESTS_DIR = 'tests';

export const DEFAULT_TEST_RUN_COMMAND = 'pnpm test';

export const DEFAULT_AI_TESTS_CONFIG = {
  sources: ['src/**/*.ts'] as string[],
  testsDir: DEFAULT_TESTS_DIR,
  runner: 'shell' as const,
  strategy: 'llm-generate' as const,
  maxAttempts: 3,
  thresholds: {
    repair: 'medium' as const
  }
};

export const KB_CONFIG_FILE = 'kb.config.json';

export const TEST_README_CONTENT = `# AI Tests Workspace

This directory holds test suites managed by KB Labs AI Tests.

- Place hand-written tests next to generated ones.
- Generated files will be marked with \`// Generated by ai-tests\`.
- Use \`kb ai-tests plan\` to update coverage targets.
`;


