import type { PluginContracts } from './types';
import { contractsSchemaId, contractsVersion } from './version';

const schemaRef = (fragment: string) => `@kb-labs/ai-tests-contracts/schema#${fragment}`;

export const pluginContractsManifest: PluginContracts = {
  schema: contractsSchemaId,
  pluginId: '@kb-labs/ai-tests',
  contractsVersion,
  artifacts: {
    'ai-tests.plan.json': {
      id: 'ai-tests.plan.json',
      kind: 'json',
      description: 'List of modules/files that require automated tests with coverage heuristics.',
      pathPattern: '.kb/artifacts/ai-tests/ai-tests.plan.json',
      mediaType: 'application/json',
      schemaRef: schemaRef('AiTestsPlanArtifactSchema')
    },
    'ai-tests.run.json': {
      id: 'ai-tests.run.json',
      kind: 'json',
      description: 'Aggregated result of the latest ai-tests:run execution.',
      pathPattern: '.kb/artifacts/ai-tests/ai-tests.run.json',
      mediaType: 'application/json',
      schemaRef: schemaRef('TestRunResultSchema')
    },
    'ai-tests.iterations.json': {
      id: 'ai-tests.iterations.json',
      kind: 'json',
      description: 'History of generate → run → repair attempts.',
      pathPattern: '.kb/artifacts/ai-tests/ai-tests.iterations.json',
      mediaType: 'application/json',
      schemaRef: schemaRef('IterationHistorySchema')
    },
    'ai-tests.metadata.json': {
      id: 'ai-tests.metadata.json',
      kind: 'json',
      description: 'Snapshot of configuration, runner mode, and strategy metadata.',
      pathPattern: '.kb/artifacts/ai-tests/metadata.json',
      mediaType: 'application/json',
      schemaRef: schemaRef('AiTestsMetadataSchema')
    },
    'ai-tests.log': {
      id: 'ai-tests.log',
      kind: 'log',
      description: 'Streaming log produced by ai-tests:run',
      pathPattern: '.kb/artifacts/ai-tests/logs/run-*.log',
      mediaType: 'text/plain'
    },
    'ai-tests.audit.md': {
      id: 'ai-tests.audit.md',
      kind: 'markdown',
      description: 'Markdown summary generated by ai-tests:audit',
      pathPattern: '.kb/artifacts/ai-tests/ai-tests.audit.md',
      mediaType: 'text/markdown'
    }
  },
  commands: {
    'ai-tests:init': {
      id: 'ai-tests:init',
      description: 'Scaffold aiTests config and tests directory.',
      input: { ref: schemaRef('InitCommandInputSchema'), format: 'zod' },
      output: { ref: schemaRef('InitCommandOutputSchema'), format: 'zod' },
      produces: ['ai-tests.metadata.json'],
      examples: ['kb ai-tests init', 'kb ai-tests init --json']
    },
    'ai-tests:plan': {
      id: 'ai-tests:plan',
      description: 'Analyse source globs and emit ai-tests.plan.json artifact.',
      input: { ref: schemaRef('PlanCommandInputSchema'), format: 'zod' },
      output: { ref: schemaRef('PlanCommandOutputSchema'), format: 'zod' },
      produces: ['ai-tests.plan.json'],
      examples: ['kb ai-tests plan', 'kb ai-tests plan --json']
    },
    'ai-tests:generate': {
      id: 'ai-tests:generate',
      description: 'Generate test suggestions or files according to the plan.',
      input: { ref: schemaRef('GenerateCommandInputSchema'), format: 'zod' },
      output: { ref: schemaRef('GenerateCommandOutputSchema'), format: 'zod' },
      produces: ['ai-tests.plan.json', 'ai-tests.iterations.json'],
      examples: ['kb ai-tests generate', 'kb ai-tests generate --strategy write-and-run']
    },
    'ai-tests:run': {
      id: 'ai-tests:run',
      description: 'Execute the configured test runner and capture structured results.',
      input: { ref: schemaRef('RunCommandInputSchema'), format: 'zod' },
      output: { ref: schemaRef('RunCommandOutputSchema'), format: 'zod' },
      produces: ['ai-tests.run.json', 'ai-tests.log']
    },
    'ai-tests:repair': {
      id: 'ai-tests:repair',
      description: 'Attempt to repair failing tests using LLM suggestions and reruns.',
      input: { ref: schemaRef('RepairCommandInputSchema'), format: 'zod' },
      output: { ref: schemaRef('RepairCommandOutputSchema'), format: 'zod' },
      produces: ['ai-tests.iterations.json', 'ai-tests.run.json', 'ai-tests.log'],
      consumes: ['ai-tests.plan.json', 'ai-tests.run.json']
    },
    'ai-tests:audit': {
      id: 'ai-tests:audit',
      description: 'Produce markdown summary combining plan, run, and iteration data.',
      input: { ref: schemaRef('AuditCommandInputSchema'), format: 'zod' },
      output: { ref: schemaRef('AuditCommandOutputSchema'), format: 'zod' },
      produces: ['ai-tests.audit.md'],
      consumes: ['ai-tests.plan.json', 'ai-tests.run.json', 'ai-tests.iterations.json']
    }
  },
  workflows: {
    'ai-tests.workflow.plan': {
      id: 'ai-tests.workflow.plan',
      description: 'Plan → generate → run lifecycle for automated tests.',
      produces: ['ai-tests.plan.json', 'ai-tests.run.json', 'ai-tests.iterations.json'],
      steps: [
        {
          id: 'ai-tests.workflow.step.plan',
          commandId: 'ai-tests:plan',
          produces: ['ai-tests.plan.json'],
          events: [
            {
              id: 'ai-tests.plan.completed',
              description: 'Plan summary with uncovered targets.',
              payload: { ref: schemaRef('PlanCommandOutputSchema'), format: 'zod' }
            }
          ]
        },
        {
          id: 'ai-tests.workflow.step.generate',
          commandId: 'ai-tests:generate',
          consumes: ['ai-tests.plan.json'],
          produces: ['ai-tests.iterations.json'],
          events: [
            {
              id: 'ai-tests.generate.progress',
              description: 'Generation progress for each uncovered module.',
              payload: { ref: schemaRef('GenerateCommandOutputSchema'), format: 'zod' }
            }
          ]
        },
        {
          id: 'ai-tests.workflow.step.run',
          commandId: 'ai-tests:run',
          consumes: ['ai-tests.plan.json'],
          produces: ['ai-tests.run.json', 'ai-tests.log'],
          events: [
            {
              id: 'ai-tests.run.completed',
              description: 'Structured result emitted after test runner finishes.',
              payload: { ref: schemaRef('RunCommandOutputSchema'), format: 'zod' }
            }
          ]
        },
        {
          id: 'ai-tests.workflow.step.repair',
          commandId: 'ai-tests:repair',
          consumes: ['ai-tests.run.json', 'ai-tests.iterations.json'],
          produces: ['ai-tests.iterations.json', 'ai-tests.run.json'],
          events: [
            {
              id: 'ai-tests.repair.attempt',
              description: 'Details about each repair iteration.',
              payload: { ref: schemaRef('RepairCommandOutputSchema'), format: 'zod' }
            }
          ]
        }
      ]
    }
  }
};

